package nlpannotator;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class ProcessMonitor extends JFrame {
    private JList list1;
    private JPanel panel1;
    private Main annotatorUI;

    private DefaultListModel<ProcessItem> itemsModel = new DefaultListModel<>();

    public ProcessMonitor(Main annotatorUI) {
        this.annotatorUI = annotatorUI;

        populate();

        setTitle("Process Monitor");
        setLocation(annotatorUI.getLocationOnScreen());
        setContentPane(panel1);
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        pack();
    }

    private void populate() {
        list1.setModel(itemsModel);
        list1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        list1.setLayoutOrientation(JList.HORIZONTAL_WRAP);
        list1.setVisibleRowCount(-1);
    }

    public String addProcess(String text) {
        ProcessItem item = new ProcessItem(text);
        itemsModel.addElement(item);

        return item.getId();
    }

    public void removeProcess(String id) {
        for (int i = 0; i < itemsModel.size(); i++) {
            ProcessItem item = itemsModel.get(i);
            if (item.getId().equals(id)) {
                itemsModel.removeElement(item);
                break;
            }
        }
    }

    public static void main(String[] args) {
        ProcessMonitor monitor = new ProcessMonitor(null);
        monitor.setVisible(true);
        String id = monitor.addProcess("testing");
        monitor.removeProcess(id);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(800, 600), new Dimension(800, 600), null, 0, false));
        list1 = new JList();
        scrollPane1.setViewportView(list1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
